let _endTime = datetime(2026-01-03T12:58:20Z);
let _startTime = datetime(2026-01-03T12:43:20Z);
SilverInverter
| where Timestamp between (_startTime .. _endTime)
  and SensorName == "Power DC Total"
| extend ValueNumeric = todouble(Value)
| extend Minute = bin(Timestamp, 1m)
| summarize LastEvent = arg_max(Timestamp, ValueNumeric) by Minute
| project Minute, Power_Watt = ValueNumeric
| order by Minute asc
| render timechart